### ISSUE TITLE
Proper error message when viewing Crate with cookies disabled (incognito mode)

### ISSUE THREAD

**Issue by SirTapTap** [widgetbot-io/embed#176] opened 2021-03-11 16:11 UTC
If you view the Crate embed in an incognito tab, you get a blank page and it never loads, logging a console error.

Makes sense since incognito is probably just disabling some feature the widgetbot embed needs to work, but it'd be nice to give a little error message to the end user stating what's occurred instead of just looking blank

Steps to reproduce: Using chrome's incognito mode opening the Crate button at https://docs.widgetbot.io/embed/crate/tutorial/

I do note that Firefox Private tab actually does work though.

**Comment by Yomanz** [comment] 2021-03-11 16:13
Duplicate of https://github.com/widgetbot-io/embed/issues/74

**Closed by Yomanz** 2021-03-11 16:13 UTC
Labels: suggestion
