### ISSUE TITLE
Blank screen bug on Brave

### ISSUE THREAD

**Issue by YamShadow** [widgetbot-io/embed#166] opened 2020-11-25 14:15 UTC
**Describe the bug**

Loading error when opening with Brave browser (updated, Version 1.17.73 Chromium: 87.0.4280.67 (Official build) (64 bits)). 
I have "getItem" error on my console. 

**To Reproduce**
1. Open with Brave Browser and open devtools

**Screenshots**
Screenshot : https://i.imgur.com/3YlmCzS.png

**Browser and version**
Brave Browser ( Version 1.17.73 Chromium: 87.0.4280.67 (Official build) (64 bits) )

**Comment by Yomanz** [comment] 2020-11-25 14:16
Thanks for the report, this is something we're already looking into :)

**Comment by advaith1** [comment] 2020-11-28 01:23
duplicate of #74

**Closed by advaith1** 2020-11-28 01:23 UTC
Labels: bug
